### ISSUE TITLE
Developer message.author.id as ENVIRONMENT variable

### ISSUE THREAD

**Issue by cwchristerw** [MatteZ02/Musix#13]
https://github.com/MatteZ02/Musix/blob/0bfa09209a697b79bed3852f636b2de232d6aa16/commands/eval.js#L11

https://github.com/MatteZ02/Musix/blob/6aa654c9e7218b5ddfbe246a67f5236c3e9b91c0/events/message.js#L5

https://github.com/MatteZ02/Musix/blob/6aa654c9e7218b5ddfbe246a67f5236c3e9b91c0/events/message.js#L17

https://github.com/MatteZ02/Musix/blob/52de7012d36181e1a9f7eddf3835466f82fb4340/commands/forcestop.js#L6

https://github.com/MatteZ02/Musix/blob/a8cde6abcaed754fe24836badd04ee59ab545961/commands/eval.js#L11

https://github.com/MatteZ02/Musix/blob/a6d4dcbcd5577cd73599bd5ef3721545cc3d0df5/commands/skip.js#L10

https://github.com/MatteZ02/Musix/blob/a6d4dcbcd5577cd73599bd5ef3721545cc3d0df5/commands/loop.js#L10

https://github.com/MatteZ02/Musix/blob/a6d4dcbcd5577cd73599bd5ef3721545cc3d0df5/commands/pause.js#L11

https://github.com/MatteZ02/Musix/blob/a6d4dcbcd5577cd73599bd5ef3721545cc3d0df5/commands/resume.js#L10

https://github.com/MatteZ02/Musix/blob/ee0d66c5543b4b2605bc2af26b4b44947fdbc061/commands/stop.js#L9

https://github.com/MatteZ02/Musix/blob/38c01032812ab97cc1933dceb6c58972e1e2c122/commands/remove.js#L15

https://github.com/MatteZ02/Musix/blob/b40bc72ead7d4bc8897624593b89d6140472ffed/commands/volume.js#L13

https://github.com/MatteZ02/Musix/blob/0bfa09209a697b79bed3852f636b2de232d6aa16/events/message.js#L63

DEV_DISCORD_UID (or similar can be name)

**Comment by cwchristerw** [comment]
This can also be separate json file when you can add multiple users that can use eval command.

**Comment by MatteZ02** [comment]
not needed

**Comment by cwchristerw** [comment]
Reopen
