### ISSUE TITLE
BOT_UID environment variable

### ISSUE THREAD

**Issue by cwchristerw** [MatteZ02/Musix#14]
https://github.com/MatteZ02/Musix/blob/0bfa09209a697b79bed3852f636b2de232d6aa16/events/message.js#L30
https://github.com/MatteZ02/Musix/blob/0bfa09209a697b79bed3852f636b2de232d6aa16/events/message.js#L31

**Comment by MatteZ02** [comment]
this will be changed in an incoming update at some point.
