### ISSUE TITLE
Debug channel ID environment variable

### ISSUE THREAD

**Issue by cwchristerw** [MatteZ02/Musix#15]
https://github.com/MatteZ02/Musix/blob/38c01032812ab97cc1933dceb6c58972e1e2c122/funcs/handleVideo.js#L35
https://github.com/MatteZ02/Musix/blob/6aa654c9e7218b5ddfbe246a67f5236c3e9b91c0/events/message.js#L64

**Comment by cwchristerw** [comment]
When running bot from different token these will cause unhandled errors because 634718645188034560 is not available to all bots.

**Comment by MatteZ02** [comment]
That is only a problem if you're running musix code. If you decide to do so you should know enough to fix that error.

**Comment by cwchristerw** [comment]
Reopen
