### ISSUE TITLE
Radio Command

### ISSUE THREAD

**Issue by cwchristerw** [MatteZ02/Musix#5]
I would like to have new `radio` command.

radio list : List different radio stations
radio play {station} (shortly radio {station}) : Play radio station

You can check here list of different radio stations
https://gitea.cwinfo.org/cwchristerw/radio

**Comment by MatteZ02** [comment]
This will be added soon

**Comment by cwchristerw** [comment]
https://github.com/warengroup/eximiabots-radiox
This is our new bot for this radio feature.
